export const COLORS = {
   primary:{
        aqua:"#039be5",
   },
   secondary:{
        pink:"#e040fb"
   },
   warning:{
       red:"#d32f2f"
   },
   grey:{
       grey:"#616161"
   },
   whiteGrey:{
      blueGray:"#004d40"
   },
   whiteOrange:{
       orange:"#ef6c00"
   }
}