import Footer from "@/components/Commons/Footer/footer";
import Navbar from "@/components/Commons/Navbar/NavigationBar";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";

const inter = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GYM__WORKOUT...",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
